name: fp_kelompok3
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  intl: ^0.18.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - Image/bumi_manusia.jpg
    - Image/BookMate.png
    - Image/onboarding1.png
    - Image/onboarding2.png
    - Image/onboarding3.png
    - Image/Logo BookMate.png
    - Image/bumi_manusia.jpg
    - Image/gadis_pantai.jpg
    - Image/mangir.jpg
    - Image/anak_semua_bangsa.jpg
    - Image/arus_balik.jpg
    - Image/jejak_langkah.jpg
    - Image/bumi_manusia_cover.jpg
    - Image/logo_bookmate.png
    - Image/filosofi_teras_cover.jpg
    - Image/gadis_pantai_cover.jpg
    - Image/hujan_cover.jpg
    - Image/laskar_pelangi_cover.jpg
    - Image/laut_bercerita_cover.jpg
    - Image/mangir_cover.jpg
    - Image/negara_5_menara_cover.jpg
    - Image/rumah_kaca_cover.jpg
    - Image/tentang_kamu_cover.jpg
    - Image/tujuh_kelana_cover.jpg
    - Image/sihir_perempuan_cover.jpg
    - Image/cantik_itu_luka_cover.jpg
    - Image/anak_semua_bangsa_cover.jpg
    - Image/gadis_kretek_cover.jpg
    - Image/sang_pemimpi_cover.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: Fonts/BeVietnamPro-Black.ttf
        - asset: Fonts/BeVietnamPro-BlackItalic.ttf
        - asset: Fonts/BeVietnamPro-Bold.ttf
        - asset: Fonts/BeVietnamPro-BoldItalic.ttf
        - asset: Fonts/BeVietnamPro-ExtraBold.ttf
        - asset: Fonts/BeVietnamPro-ExtraBoldItalic.ttf
        - asset: Fonts/BeVietnamPro-ExtraLight.ttf
        - asset: Fonts/BeVietnamPro-ExtraLightItalic.ttf
        - asset: Fonts/BeVietnamPro-Italic.ttf
        - asset: Fonts/BeVietnamPro-Light.ttf
        - asset: Fonts/BeVietnamPro-LightItalic.ttf
        - asset: Fonts/BeVietnamPro-Medium.ttf
        - asset: Fonts/BeVietnamPro-MediumItalic.ttf
        - asset: Fonts/BeVietnamPro-Regular.ttf
        - asset: Fonts/BeVietnamPro-SemiBold.ttf
        - asset: Fonts/BeVietnamPro-SemiBoldItalic.ttf
        - asset: Fonts/BeVietnamPro-Thin.ttf
        - asset: Fonts/BeVietnamPro-ThinItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
